# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: octane-start-task@2
  inputs:
    OctaneServiceConnection: 'jg_ADO_VE'
    WorkspaceList: '8001'
    CreatePipelineCheckbox: true


- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: srlTest@0
  inputs:
    serverEndpoint: 'LRC Connection'
    tenantid: '688301833'
    projectid: '157'
    testid: '1420'
    sendEmail: true
- task: octane-end-task@2
  inputs:
    OctaneServiceConnection: 'jg_ADO_VE'
    WorkspaceList: '8001'