trigger:
- main

jobs:
- job: AlmOctaneStartJob
  condition: always()
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: octane-start-task@2
    inputs:
      OctaneServiceConnection: 'jg_ADO_VE'
      WorkspaceList: '8001'
      CreatePipelineCheckbox: true

- job: LRCRun
  pool: 
    vmImage: ubuntu-latest
  dependsOn:
  - AlmOctaneStartJob
  steps:
  - task: srlTest@0
    inputs:
      serverEndpoint: 'LRC Connection'
      tenantid: '688301833'
      projectid: '157'
      testid: '1387'
      sendEmail: true
  - script: echo Run Id of the LRC run ${LRC.LRC_RUN_ID}
    displayName: 'Catch the Run Id of the LRC run'

- job: AlmOctaneEndJob
  condition: always()
  pool:
    vmImage: ubuntu-latest
  dependsOn:
  - AlmOctaneStartJob
  - LRCRun
  steps:
  - task: octane-end-task@2
    inputs:
      OctaneServiceConnection: 'jg_ADO_VE'
      WorkspaceList: '8001'
